version: "3.8"
   
services:
  pgAdmin:
        restart: always
        image: dpage/pgadmin4
        ports:
            - "8000:89"
        environment:
            PGADMIN_DEFAULT_EMAIL: 1234@admin.com
            PGADMIN_DEFAULT_PASSWORD: 1234
        volumes:
            - pgadmin:/var/lib/pgadmin
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
            - "5432:5432"
    volumes:
      - pgvol:/var/lib/postgresql/data
      
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8887"
    volumes:
      - .:/code
    ports:
      - "8887:8887"
    depends_on:
      - db
   
  volumes:
     pgadmin:
     pgvol:

